package util;

import java.util.HashSet;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class FirstFollow {
    public final String Version;
    public final String StartSymbol;
    public final String About;
    public final String Author;
    public final String Name;
    public final String CaseSensitive;
    private HashMap<String, HashSet<String>> first;
    private HashMap<String, HashSet<String>> follow;
    private static FirstFollow instance;

    private FirstFollow() {
        this.Version = "The version of the grammar and/or language";
        this.StartSymbol = "<Program>";
        this.About = "A short description of the grammar";
        this.Author = "João Victor, Eduardo Marques, Gustavo Henrique, Marcos Aldrey, Marcos Vinicius, Alyson, Alisson, André, Gilvaney, Nielson, Lucas Cardoso";
        this.Name = "RICHARD";
        this.CaseSensitive = "True";
        this.first = new HashMap<>();
        this.first.put("Initialize", new HashSet<>(Arrays.asList("", "=")));
        this.first.put("Call Arguments", new HashSet<>(Arrays.asList("", "(")));
        this.first.put("Arguments", new HashSet<>(Arrays.asList("false", "StringLiteral", "", "true", "{", "NumberTerminal", "Identifier")));
        this.first.put("Valid Values", new HashSet<>(Arrays.asList("false", "StringLiteral", "true", "NumberTerminal", "Identifier")));
        this.first.put("Expr Arit", new HashSet<>(Arrays.asList("false", "StringLiteral", "-", "true", "{", "NumberTerminal", "Identifier")));
        this.first.put("Init Array_1", new HashSet<>(Arrays.asList("", "(")));
        this.first.put("Arithmetic", new HashSet<>(Arrays.asList("+", "", "-")));
        this.first.put("Array", new HashSet<>(Arrays.asList("", "[")));
        this.first.put("Init Array_3", new HashSet<>(Arrays.asList("false", "StringLiteral", "true", "{", "NumberTerminal", "Identifier")));
        this.first.put("Return Statement", new HashSet<>(Arrays.asList("Identifier", "-", "{", "(", "false", "StringLiteral", "true", "NumberTerminal", "!", "")));
        this.first.put("Multiple", new HashSet<>(Arrays.asList("/", "*", "")));
        this.first.put("Negate Exp", new HashSet<>(Arrays.asList("false", "StringLiteral", "-", "true", "{", "NumberTerminal", "Identifier")));
        this.first.put("Type", new HashSet<>(Arrays.asList("bool", "Identifier", "float", "int", "void", "string")));
        this.first.put("Code Block", new HashSet<>(Arrays.asList("{")));
        this.first.put("Post-Else-Block", new HashSet<>(Arrays.asList("if", "", "{")));
        this.first.put("Extends", new HashSet<>(Arrays.asList("extends", "")));
        this.first.put("Increment-Decrement", new HashSet<>(Arrays.asList("--", "", "++")));
        this.first.put("If-Block", new HashSet<>(Arrays.asList("if")));
        this.first.put("Execute Line", new HashSet<>(Arrays.asList("++", "(", "--", "=")));
        this.first.put("Program", new HashSet<>(Arrays.asList("const", "", "class")));
        this.first.put("Initialize Variable", new HashSet<>(Arrays.asList(",", "")));
        this.first.put("Initialize Constant", new HashSet<>(Arrays.asList(",", "", "=")));
        this.first.put("Relational Operator", new HashSet<>(Arrays.asList("<=", "!=", "==", "<", ">", ">=")));
        this.first.put("Relational Logic", new HashSet<>(Arrays.asList("<=", "||", ">=", "==", "<", "&&", ">", "", "!=")));
        this.first.put("Methods", new HashSet<>(Arrays.asList("method")));
        this.first.put("Declaration", new HashSet<>(Arrays.asList("bool", "Identifier", "float", "int", "string", "void")));
        this.first.put("Multiple Identifier", new HashSet<>(Arrays.asList(",", "")));
        this.first.put("Logic Operator", new HashSet<>(Arrays.asList("||", "&&")));
        this.first.put("Constant Assignment", new HashSet<>(Arrays.asList("bool", "Identifier", "float", "", "int", "void", "string")));
        this.first.put("Valid Identifier", new HashSet<>(Arrays.asList("Identifier")));
        this.first.put("Init Array_4", new HashSet<>(Arrays.asList(",", "")));
        this.first.put("Write Parameters", new HashSet<>(Arrays.asList("false", "StringLiteral", "true", "NumberTerminal", "Identifier")));
        this.first.put("Expression", new HashSet<>(Arrays.asList("Identifier", "false", "StringLiteral", "-", "true", "{", "NumberTerminal", "(")));
        this.first.put("Value", new HashSet<>(Arrays.asList("true", "false", "StringLiteral", "NumberTerminal")));
        this.first.put("Parameter", new HashSet<>(Arrays.asList(",", "")));
        this.first.put("Class", new HashSet<>(Arrays.asList("class")));
        this.first.put("Negate", new HashSet<>(Arrays.asList("!", "")));
        this.first.put("Attribute Access", new HashSet<>(Arrays.asList(".", "")));
        this.first.put("Array Position", new HashSet<>(Arrays.asList("Identifier", "-", "{", "(", "false", "StringLiteral", "true", "NumberTerminal", "")));
        this.first.put("Mult Exp", new HashSet<>(Arrays.asList("false", "StringLiteral", "-", "true", "{", "Identifier", "NumberTerminal")));
        this.first.put("Write", new HashSet<>(Arrays.asList("write")));
        this.first.put("Argument", new HashSet<>(Arrays.asList(",", "")));
        this.first.put("Constants", new HashSet<>(Arrays.asList("const")));
        this.first.put("Read", new HashSet<>(Arrays.asList("read")));
        this.first.put("Identifier With Attributes", new HashSet<>(Arrays.asList("Identifier")));
        this.first.put("Read Parameters", new HashSet<>(Arrays.asList(",", "")));
        this.first.put("Code Statements", new HashSet<>(Arrays.asList("", "Identifier", "variables", "return", "write", "while", "read", "if")));
        this.first.put("Method Call", new HashSet<>(Arrays.asList("Identifier")));
        this.first.put("Class Code", new HashSet<>(Arrays.asList("", "method", "variables")));
        this.first.put("Parameters", new HashSet<>(Arrays.asList("bool", "Identifier", "float", "", "int", "void", "string")));
        this.first.put("Variables", new HashSet<>(Arrays.asList("variables")));
        this.first.put("Line Code", new HashSet<>(Arrays.asList("Identifier", "write", "read", "return")));
        this.first.put("To-Write", new HashSet<>(Arrays.asList(",", "")));
        this.first.put("Variable Assignment", new HashSet<>(Arrays.asList("bool", "Identifier", "float", "", "int", "void", "string")));
        this.first.put("Looping-Block", new HashSet<>(Arrays.asList("while")));
        this.first.put("Attribution", new HashSet<>(Arrays.asList("--", "++", "=")));
        this.first.put("Initial Value", new HashSet<>(Arrays.asList("false", "StringLiteral", "true", "{", "Identifier", "NumberTerminal")));
        this.first.put("Else-Block", new HashSet<>(Arrays.asList("else", "")));
        this.first.put("Init Array_2", new HashSet<>(Arrays.asList("(")));
        this.first.put("Condition", new HashSet<>(Arrays.asList("Identifier", "-", "{", "(", "false", "StringLiteral", "true", "NumberTerminal", "!")));
        this.first.put("Init Array", new HashSet<>(Arrays.asList("{")));
        this.follow = new HashMap<>();
        this.follow.put("Initialize", new HashSet<>(Arrays.asList("bool", "Identifier", "float", "variables", "int", "string", "void")));
        this.follow.put("Call Arguments", new HashSet<>(Arrays.asList("++", "--", ";", "read", ",")));
        this.follow.put("Write Parameters", new HashSet<>(Arrays.asList("write")));
        this.follow.put("Valid Values", new HashSet<>(Arrays.asList("--", "write", ",", "read", "++")));
        this.follow.put("Init Array_1", new HashSet<>(Arrays.asList("{")));
        this.follow.put("Init Array", new HashSet<>(Arrays.asList(",")));
        this.follow.put("Type", new HashSet<>(Arrays.asList("Identifier")));
        this.follow.put("Init Array_2", new HashSet<>(Arrays.asList("{")));
        this.follow.put("Extends", new HashSet<>(Arrays.asList("class")));
        this.follow.put("Execute Line", new HashSet<>(Arrays.asList(";")));
        this.follow.put("Arguments", new HashSet<>(Arrays.asList("--", "Identifier", ",", "++", ";", "read", "(")));
        this.follow.put("Negate Exp", new HashSet<>(Arrays.asList("/", "*")));
        this.follow.put("Array Position", new HashSet<>(Arrays.asList("[")));
        this.follow.put("Constants", new HashSet<>(Arrays.asList("class", "const")));
        this.follow.put("Post-Else-Block", new HashSet<>(Arrays.asList("Identifier", "write", "return", "if", "while", "read", "variables")));
        this.follow.put("Value", new HashSet<>(Arrays.asList(",", "write", "++", "read", "--")));
        this.follow.put("Increment-Decrement", new HashSet<>(Arrays.asList("/", "Identifier", ",", ";", "*", "(")));
        this.follow.put("If-Block", new HashSet<>(Arrays.asList("Identifier", "if", "variables", "write", "while", "read", "return")));
        this.follow.put("Relational Operator", new HashSet<>(Arrays.asList("Identifier", "-", "{", "(", "false", "StringLiteral", "true", "NumberTerminal", "!")));
        this.follow.put("Program", new HashSet<>(Arrays.asList("$")));
        this.follow.put("Looping-Block", new HashSet<>(Arrays.asList("Identifier", "if", "variables", "write", "while", "read", "return")));
        this.follow.put("Argument", new HashSet<>(Arrays.asList("Identifier", "(")));
        this.follow.put("Else-Block", new HashSet<>(Arrays.asList("Identifier", "return", "variables", "while", "if", "read", "write")));
        this.follow.put("Logic Operator", new HashSet<>(Arrays.asList("Identifier", "-", "{", "(", "false", "StringLiteral", "true", "NumberTerminal", "!")));
        this.follow.put("Methods", new HashSet<>(Arrays.asList("method", "variables")));
        this.follow.put("Declaration", new HashSet<>(Arrays.asList(",", "method", "=")));
        this.follow.put("Expr Arit", new HashSet<>(Arrays.asList("bool", ";", "=", "string", "false", "StringLiteral", "NumberTerminal", ",", "Identifier", "-", "{", "(", "const", "float", "void", "true", "[", "!", "int")));
        this.follow.put("Condition", new HashSet<>(Arrays.asList("Identifier", "-", "{", "(", ";", "false", "StringLiteral", "if", "true", "NumberTerminal", "!", "while")));
        this.follow.put("Constant Assignment", new HashSet<>(Arrays.asList("const")));
        this.follow.put("Valid Identifier", new HashSet<>(Arrays.asList(",", ".", "method", "=")));
        this.follow.put("Init Array_4", new HashSet<>(Arrays.asList(",", "(")));
        this.follow.put("Parameters", new HashSet<>(Arrays.asList("method")));
        this.follow.put("Parameter", new HashSet<>(Arrays.asList("method")));
        this.follow.put("Init Array_3", new HashSet<>(Arrays.asList(",", "(")));
        this.follow.put("Relational Logic", new HashSet<>(Arrays.asList("Identifier", "-", "{", "(", "false", "StringLiteral", "while", "true", "if", "!", "NumberTerminal")));
        this.follow.put("Class", new HashSet<>(Arrays.asList("class", "const")));
        this.follow.put("Negate", new HashSet<>(Arrays.asList("false", "Identifier", "StringLiteral", "-", "true", "{", "NumberTerminal", "(")));
        this.follow.put("Attribute Access", new HashSet<>(Arrays.asList("++", "(", "--", "=")));
        this.follow.put("Code Block", new HashSet<>(Arrays.asList("return", "Identifier", "method", "variables", "while", "if", "read", "write")));
        this.follow.put("Mult Exp", new HashSet<>(Arrays.asList("-", "+")));
        this.follow.put("Write", new HashSet<>(Arrays.asList(";")));
        this.follow.put("Initialize Constant", new HashSet<>(Arrays.asList("bool", "Identifier", "float", "const", "int", "string", "void")));
        this.follow.put("Expression", new HashSet<>(Arrays.asList("bool", ";", "=", "string", "false", "StringLiteral", "NumberTerminal", ",", "Identifier", "-", "{", "(", "[", "float", "void", "true", "const", "!", "int")));
        this.follow.put("Read", new HashSet<>(Arrays.asList(";")));
        this.follow.put("Identifier With Attributes", new HashSet<>(Arrays.asList("++", "=", "--", "(")));
        this.follow.put("Read Parameters", new HashSet<>(Arrays.asList("read")));
        this.follow.put("Code Statements", new HashSet<>(Arrays.asList("{")));
        this.follow.put("Method Call", new HashSet<>(Arrays.asList(",")));
        this.follow.put("Class Code", new HashSet<>(Arrays.asList("class")));
        this.follow.put("Multiple", new HashSet<>(Arrays.asList("+", "-")));
        this.follow.put("Variables", new HashSet<>(Arrays.asList("if", "Identifier", "method", "variables", "write", "while", "read", "return")));
        this.follow.put("Line Code", new HashSet<>(Arrays.asList(";")));
        this.follow.put("To-Write", new HashSet<>(Arrays.asList("write")));
        this.follow.put("Variable Assignment", new HashSet<>(Arrays.asList("variables")));
        this.follow.put("Return Statement", new HashSet<>(Arrays.asList("Identifier", "-", "{", "(", "false", "StringLiteral", "true", "NumberTerminal", "!", ";")));
        this.follow.put("Attribution", new HashSet<>(Arrays.asList(";")));
        this.follow.put("Initial Value", new HashSet<>(Arrays.asList("/", "Identifier", "*", ",", "(")));
        this.follow.put("Arithmetic", new HashSet<>(Arrays.asList("bool", "Identifier", "float", "-", "(", "{", "NumberTerminal", "=", "string", "false", "StringLiteral", ",", "true", "int", "!", "void")));
        this.follow.put("Array", new HashSet<>(Arrays.asList(",", "method", ".", "=")));
        this.follow.put("Initialize Variable", new HashSet<>(Arrays.asList("bool", "Identifier", "float", "variables", "int", "string", "void")));
        this.follow.put("Multiple Identifier", new HashSet<>(Arrays.asList("=")));
    }

    public HashMap<String, List<List<String>>> getProductions() {
        HashMap<String, List<List<String>>> productions = new HashMap<>();
        productions.put("<Value>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'true'")), new ArrayList<>(Arrays.asList("'false'")), new ArrayList<>(Arrays.asList("StringLiteral")), new ArrayList<>(Arrays.asList("NumberTerminal")))));
        productions.put("<Call Arguments>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'('", "<Arguments>", "')'")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Arguments>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Initial Value>", "<Argument>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Valid Values>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Value>")), new ArrayList<>(Arrays.asList("<Identifier With Attributes>", "<Call Arguments>")))));
        productions.put("<Expr Arit>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Mult Exp>", "<Arithmetic>")))));
        productions.put("<Write Parameters>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Valid Values>", "<To-Write>")), new ArrayList<>(Arrays.asList("<Method Call>", "<To-Write>")))));
        productions.put("<To-Write>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<Valid Values>", "<To-Write>")), new ArrayList<>(Arrays.asList("','", "<Method Call>", "<To-Write>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Variable Assignment>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Declaration>", "<Initialize>", "<Initialize Variable>", "';'", "<Variable Assignment>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Read Parameters>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<Valid Values>", "<Read Parameters>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Return Statement>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Condition>")), new ArrayList<>(Arrays.asList("'('", "<Return Statement>", "')'")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Initialize>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'='", "<Expression>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Negate Exp>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'-'", "<Initial Value>")), new ArrayList<>(Arrays.asList("<Initial Value>")))));
        productions.put("<Init Array_2>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'('", "<Init Array_3>", "')'", "<Init Array_1>")))));
        productions.put("<Constants>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'const'", "'{'", "<Constant Assignment>", "'}'")))));
        productions.put("<Post-Else-Block>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<If-Block>")), new ArrayList<>(Arrays.asList("<Code Block>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Looping-Block>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'while'", "'('", "<Condition>", "')'", "<Code Block>")))));
        productions.put("<Increment-Decrement>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'++'", "<Increment-Decrement>")), new ArrayList<>(Arrays.asList("'--'", "<Increment-Decrement>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<If-Block>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'if'", "'('", "<Condition>", "')'", "'then'", "<Code Block>", "<Else-Block>")))));
        productions.put("<Else-Block>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'else'", "<Post-Else-Block>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Program>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Class>", "<Program>")), new ArrayList<>(Arrays.asList("<Constants>", "<Program>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Line Code>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'return'", "<Return Statement>")), new ArrayList<>(Arrays.asList("<Read>")), new ArrayList<>(Arrays.asList("<Write>")), new ArrayList<>(Arrays.asList("<Identifier With Attributes>", "<Execute Line>")))));
        productions.put("<Execute Line>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Attribution>")), new ArrayList<>(Arrays.asList("<Call Arguments>")))));
        productions.put("<Array Position>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Expression>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Argument>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<Initial Value>", "<Argument>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Methods>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'method'", "<Declaration>", "'('", "<Parameters>", "')'", "<Code Block>")))));
        productions.put("<Declaration>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Type>", "<Valid Identifier>")))));
        productions.put("<Constant Assignment>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Declaration>", "'='", "<Expression>", "<Initialize Constant>", "';'", "<Constant Assignment>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Code Block>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'{'", "<Code Statements>", "'}'")))));
        productions.put("<Attribute Access>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'.'", "<Identifier With Attributes>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Condition>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'('", "<Condition>", "')'", "<Relational Logic>")), new ArrayList<>(Arrays.asList("<Negate>", "<Expression>", "<Relational Logic>")))));
        productions.put("<Init Array_4>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<Init Array_3>", "<Init Array_4>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Parameter>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<Parameters>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Parameters>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Declaration>", "<Parameter>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Class>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'class'", "Identifier", "<Extends>", "'{'", "<Class Code>", "'}'")))));
        productions.put("<Class Code>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Variables>", "<Class Code>")), new ArrayList<>(Arrays.asList("<Methods>", "<Class Code>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Logic Operator>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'&&'")), new ArrayList<>(Arrays.asList("'||'")))));
        productions.put("<Negate>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'!'", "<Negate>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Multiple Identifier>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("','", "<Valid Identifier>", "<Multiple Identifier>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Relational Logic>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Relational Operator>", "<Condition>")), new ArrayList<>(Arrays.asList("<Logic Operator>", "<Condition>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Mult Exp>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Negate Exp>", "<Multiple>")))));
        productions.put("<Write>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'write'", "'('", "<Write Parameters>", "')'")))));
        productions.put("<Initialize Constant>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Multiple Identifier>", "'='", "<Expression>", "<Initialize Constant>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Initialize Variable>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Multiple Identifier>", "<Initialize>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Read>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'read'", "'('", "<Valid Values>", "<Read Parameters>", "')'")))));
        productions.put("<Identifier With Attributes>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Valid Identifier>", "<Attribute Access>")))));
        productions.put("<Relational Operator>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'!='")), new ArrayList<>(Arrays.asList("'=='")), new ArrayList<>(Arrays.asList("'<'")), new ArrayList<>(Arrays.asList("'<='")), new ArrayList<>(Arrays.asList("'>'")), new ArrayList<>(Arrays.asList("'>='")))));
        productions.put("<Code Statements>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<If-Block>", "<Code Statements>")), new ArrayList<>(Arrays.asList("<Looping-Block>", "<Code Statements>")), new ArrayList<>(Arrays.asList("<Line Code>", "';'", "<Code Statements>")), new ArrayList<>(Arrays.asList("<Variables>", "<Code Statements>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Method Call>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Identifier With Attributes>", "'('", "<Arguments>", "')'")))));
        productions.put("<Extends>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'extends'", "Identifier")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Multiple>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'*'", "<Expression>")), new ArrayList<>(Arrays.asList("'/'", "<Expression>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Variables>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'variables'", "'{'", "<Variable Assignment>", "'}'")))));
        productions.put("<Init Array_3>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Initial Value>", "<Init Array_4>")))));
        productions.put("<Expression>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'('", "<Expr Arit>", "')'")), new ArrayList<>(Arrays.asList("<Expr Arit>")))));
        productions.put("<Array>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'['", "<Array Position>", "']'", "<Array>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Valid Identifier>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("Identifier", "<Array>")))));
        productions.put("<Attribution>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'='", "<Expression>")), new ArrayList<>(Arrays.asList("<Increment-Decrement>")))));
        productions.put("<Initial Value>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Init Array>")), new ArrayList<>(Arrays.asList("<Valid Values>", "<Increment-Decrement>")))));
        productions.put("<Arithmetic>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'+'", "<Expression>")), new ArrayList<>(Arrays.asList("'-'", "<Expression>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Type>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'string'")), new ArrayList<>(Arrays.asList("'int'")), new ArrayList<>(Arrays.asList("'float'")), new ArrayList<>(Arrays.asList("'bool'")), new ArrayList<>(Arrays.asList("'void'")), new ArrayList<>(Arrays.asList("Identifier")))));
        productions.put("<Init Array_1>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("<Init Array_2>")), new ArrayList<>(Arrays.asList("")))));
        productions.put("<Init Array>", new ArrayList<>(Arrays.asList(new ArrayList<>(Arrays.asList("'{'", "<Init Array_2>", "'}'")))));
        return productions;
    }

    public HashMap<String, HashSet<String>> getFirst() {
        return this.first;
    }

    public HashMap<String, HashSet<String>> getFollow() {
        return this.follow;
    }

    public static FirstFollow getInstance() {
        if (instance == null) {
            instance = new FirstFollow();
        }
        return instance;
    }
}
